version: "3.7"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/:/code/
    ports:
      - 8000:$APP_PORT
    depends_on:
      - db
    command: ./wait-for-it.sh db:5432 -- ./entrypoint.sh
    environment:
      DEFAULT_ROOT_USER: root
    env_file:
      - .env

  db:
    image: postgres:11-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env


volumes:
  postgres_data:
