version: "3.7"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/:/code/
    ports:
      - 8000:$APP_PORT
    command: ./entrypoint.sh
    environment:
      DEFAULT_ROOT_USER: pass
    env_file:
      - .env
