---
resources:
  - name: main-repo-infrastructure
    type: git
    icon: github
    source:
      uri: https://github.com/kharandziuk/django-login-example
      branch: main
      paths:
      - "/infrastructure"

jobs:
  - name: deploy-staging
    plan:
      - get: main-repo-infrastructure
        trigger: true
      - task: terraform
        config:
          inputs:
            - name: main-repo-infrastructure
          platform: linux

          image_resource:
            type: docker-image
            source:
              image: python:3.8-alpine

          run:
            path: bash
            args:
            - -exc
            - |
              ls
              wget https://releases.hashicorp.com/terraform/0.12.21/terraform_0.12.21_linux_amd64.zip
              RUN unzip terraform_0.12.21_linux_amd64.zip && rm terraform_0.12.21_linux_amd64.zip
              mv terraform /usr/bin/terraform
              pip3 install -r requirements.txt
              inv get-identity
