resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: pull-request
    type: pull-request
    check_every: 15s
    webhook_token: ((webhook-token))
    source:
      repository: kharandziuk/django-login-example
      access_token: ((github-access-token))

jobs:
  - name: print-creds
    plan:
    - get: pull-request
      trigger: true
      version: every
    - put: pull-request
      params:
        path: pull-request
        status: pending
    - task: unit-test
      privileged: true
      file: pull-request/CI/unit-tests.yml
      on_failure:
         put: pull-request
         params:
           path: pull-request
           status: failure
    - put: pull-request
      params:
        path: pull-request
        status: success
