---
resources:
  - name: main-repo
    type: git
    icon: github
    source:
      uri: https://github.com/kharandziuk/django-login-example


jobs:
  # update this pipeline before updating child pipelines
  - name: set-self
    public: true
    plan:
      - get: main-repo
        trigger: true
      - set_pipeline: set-pipelines
        file: main-repo/CI/set-pipeline.yml

  - name: validate-code
    plan:
      - get: main-repo
        trigger: true
      - task: validate-code
        file: main-repo/CI/validate.yml
      - task: validate-terraform
        file: main-repo/CI/validate-terraform.yml
