---
resources:
  - name: main-repo
    type: git
    icon: github
    source:
      uri: https://github.com/kharandziuk/django-login-example


jobs:
  # update this pipeline before updating child pipelines
  - name: set-self
    public: true
    plan:
      - get: main-repo
        trigger: true
      - set_pipeline: set-pipelines
        file: main-repo/CI/set_pipeline.yml

  - name: validate styles
    plan:
      - get: main-repo
        trigger: true
      - run:
        path: sh
        args:
        - -exc
        - |
          whoami
